services:
  stacks-blockchain-postgres:
    restart: always
    image: postgres:15.6
    container_name: stacks_postgres
    command: postgres -c 'max_connections=1000'
    shm_size: 2gb
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6nyi11z9tWbXJDYsVESHQfNVo
      POSTGRES_DB: stacks_blockchain_api
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  stacks-blockchain-api:
    restart: always
    image: bestmike007/stacks-blockchain-api:7.8.2
    container_name: stacks_api
    entrypoint: "/wait"
    network_mode: host
    environment:
      WAIT_HOSTS: "127.0.0.1:5432"
      WAIT_COMMAND: "node ./lib/index.js"
      PG_HOST: 127.0.0.1
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 6nyi11z9tWbXJDYsVESHQfNVo
      PG_DATABASE: stacks_blockchain_api
      PG_SCHEMA: stacks_blockchain_api
      STACKS_CORE_EVENT_PORT: "3700"
      STACKS_CORE_EVENT_HOST: http://0.0.0.0
      STACKS_BLOCKCHAIN_API_PORT: "3999"
      STACKS_BLOCKCHAIN_API_HOST: 0.0.0.0
      STACKS_CORE_RPC_HOST: 127.0.0.1
      STACKS_CORE_RPC_PORT: "20443"
      STACKS_CHAIN_ID: "0x00000001"
      STACKS_API_ENABLE_FT_METADATA: 1
      STACKS_API_ENABLE_NFT_METADATA: 1
      NODE_ENV: production
    volumes:
      - ./wait:/wait:ro
  stacks-blockchain:
    restart: always
    image: bestmike007/stacks-blockchain:2.4.0.1.0
    container_name: stacks_node
    entrypoint: "/wait"
    network_mode: host
    environment:
      WAIT_BEFORE: 3
      WAIT_AFTER: 3
      WAIT_HOSTS: "127.0.0.1:3700"
      WAIT_COMMAND: "stacks-node start --config /srv/Stacks.toml"
      NOP_BLOCKSTACK_DEBUG: 0
      XBLOCKSTACK_DEBUG: 0
      RUST_BACKTRACE: 0
      STACKS_CHAIN_ID: "0x00000001"
      V2_POX_MIN_AMOUNT_USTX: 90000000260
      STACKS_CORE_RPC_HOST: 127.0.0.1
      STACKS_CORE_RPC_PORT: 20443
      STACKS_API_ENABLE_FT_METADATA: 1
      STACKS_API_ENABLE_NFT_METADATA: 1
    volumes:
      - ./config/Stacks.toml:/srv/Stacks.toml:ro
      - ./stacks-node/mainnet:/srv/stacks-node/mainnet
      - ./wait:/wait:ro
